### PR TITLE
fix: undefined error empty process/subprocesses

### LINKED ISSUE #43: `TypeError: Cannot read properties of undefined (reading 'filter')`
### Describe the Bug

I refactored [`example.js`](https://github.com/bpmn-io/bpmn-auto-layout/blob/main/example.js) imports. In the end, I run the script to see how the `layoutProcess` function will set di elements for the bpmn structure. But unfortunately, it throws an error:

```js
file:///home/corocoto/Documents/Github/bpmn-auto-layout/dist/index.esm.js:707
    const startingElements = flowElements.filter(el => {
                                          ^

TypeError: Cannot read properties of undefined (reading 'filter')
    at Layouter.createGridLayout (file:///home/corocoto/Documents/Github/bpmn-auto-layout/dist/index.esm.js:707:43)
    at Layouter.handlePlane (file:///home/corocoto/Documents/Github/bpmn-auto-layout/dist/index.esm.js:694:25)
    at Layouter.createGridLayout (file:///home/corocoto/Documents/Github/bpmn-auto-layout/dist/index.esm.js:732:14)
    at Layouter.handlePlane (file:///home/corocoto/Documents/Github/bpmn-auto-layout/dist/index.esm.js:694:25)
    at Layouter.layoutProcess (file:///home/corocoto/Documents/Github/bpmn-auto-layout/dist/index.esm.js:688:10)
    at async file:///home/corocoto/Documents/Github/bpmn-auto-layout/example.js:65:28
``` 

### Steps to Reproduce

1. Open [a test project in the Replit](https://replit.com/@corocoto/bpmn-auto-layout-di-error)
2. Click onto the "Run" button

### Expected Behavior

The script will print a new bpmn structure into a console and also will write it into `layouted.bpmn` file.

### Environment

- Host (Browser/Node version), if applicable: Node v20.11.1
- OS: Linux Mint 20.3 x86_64
- Library version: Latest

### PR DESCRIPTION
**Pull request by abdul99ahad**
Closes #43

### Proposed Changes

- [ ] Empty subprocesses no longer throws error and returns the grid.

 

### Checklist

To ensure you provided everything we need to look at your PR:

* [ ] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [ ] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

File: lib/Layouter.js [hunk 1]
```diff
@@ -47,6 +47,11 @@ export class Layouter {
 
     const flowElements = root.flowElements;
```
Comment (nikku) [inline lib/Layouter.js:48]: Alternative ([null object pattern](https://en.wikipedia.org/wiki/Null_object_pattern)): 

```suggestion
    const flowElements = root.flowElements || [];
```

Comment (abdul99ahad) [reply lib/Layouter.js]: Thanks for the suggestion, resolved.

**Review by nikku — APPROVED** [review]
